version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency-base
    working_dir: /usr/src/myapp
    container_name: nest-microservice-container
    restart: unless-stopped

    volumes:
      - ./:/usr/src/myapp

    stdin_open: true
    ports:
      - "${APP_PORT:-80}:3000"
      - "${PRISMA_STUDIO_PORT:-5555}:5555"
      - "9229:9229"

    networks:
      - diego-network
  
  postgres:
    container_name: nest-microservice-postgress
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
    networks:
      - diego-network

  mongo:
    image: "mongo:6.0"
    container_name: nest-microservice-mongodb
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - "${DB_PORT_INTERNAL_LOCALHOST_MONGODB:-27017}:${DB_PORT_MONGODB:-27017}"
    environment:
      - MONGODB_DATABASE="vf-read-db"
    networks:
      - diego-network

  event-store:
    image: mongo:6.0.4
    container_name: nest-microservice-mongodb-event-store
    ports:
      - "27018:27017"
    environment:
      - MONGODB_DATABASE="vf-event-store"
    command: "mongod --replSet vf-event-store-repl-set"
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - diego-network

networks:
  diego-network:
    external:
      name: diego-shared-network
